#!/usr/bin/env node
/**
 * Agent runner — self-contained Node ESM script.
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Generated from scripts/lib/agentRunnerTemplate.mjs — run:
 *   node scripts/lib/agentRunnerTemplate.mjs > scripts/agent-runner/run.mjs
 *
 * Env contract (all required unless noted):
 *   ANTHROPIC_API_KEY   — Anthropic key (scoped, spend-capped)
 *   CONVEX_URL          — Convex deployment URL
 *   JOB_TOKEN           — HMAC-signed job token (passed as arg to every bridge call)
 *   versionId           — Convex version doc id
 *   threadId            — Convex thread id
 *   promptMessageId     — Convex message id for the initial prompt
 *   model               — Claude model slug
 *   effort              — "low" | "medium" | "high"
 *   kit                 — starter kit name
 *   isEdit              — "true" | "false"
 *   styleDirective      — (optional) extra style instruction
 *
 * Bridge: outbound-only Convex mutations via plain HTTP
 *   POST {CONVEX_URL}/api/mutation  { path: "agentBridge:X", args: { jobToken, ...} }
 *   JOB_TOKEN is an HMAC arg on every call — no custom request headers.
 *
 * Agent SDK API (documented at code.claude.com/docs/en/agent-sdk/typescript):
 *   query({ prompt, options }) → AsyncGenerator<SDKMessage>
 *   options.permissionMode = "dontAsk"  (camelCase)
 *   options.allowedTools   = ["Read","Write","Edit","Bash","Glob","Grep"]
 *   options.hooks.preToolUse  — array of { match, handler } objects
 *   options.hooks.postToolUse — array of { match, handler } objects
 *   Write hook input: { path, content }; Edit hook input: { path, edits[] }
 *   Multi-turn: query.streamInput(asyncIterable) feeds follow-up user messages
 *
 * Flags:
 *   --self-test         — run pure-logic self-tests and exit 0 (no network)
 */

// ═══════════════════════════════════════════════════════════════════════════════
// INLINED PURE LOGIC (generated from convex/lib/agentRunner/*.ts)
// ═══════════════════════════════════════════════════════════════════════════════

// ── forbidden.ts ──────────────────────────────────────────────────────────────
export const FORBIDDEN_PATHS = new Set([
  "package.json",
  "package-lock.json",
  "app.json",
  "tsconfig.json",
  "tsconfig.base.json",
  "babel.config.js",
  "babel.config.ts",
  "metro.config.js",
  "metro.config.ts",
  "expo.config.js",
  "expo.config.ts",
  // NativeWind snapshot infra — baked once, never repaired.
  "tailwind.config.js",
  "tailwind.config.ts",
  "global.css",
  "nativewind-env.d.ts",
  "postcss.config.js",
]);

/** Returns true if the given file path is forbidden (must not be written). */
export function isForbiddenPath(filePath) {
  const normalized = filePath.replace(/^\.\//, "");
  return FORBIDDEN_PATHS.has(normalized);
}

// ── overlay.ts ────────────────────────────────────────────────────────────────
/**
 * Returns true if the HTML response looks like a Metro bundler error overlay
 * rather than a healthy bundle. Checks only unambiguous error-specific markers
 * that do NOT appear in healthy bundles.
 */
export function looksLikeMetroOverlay(html) {
  const markers = [
    // Metro bundler error — appears in "Unable to resolve module" pages
    "Unable to resolve module",
    // Metro compile-time failure
    "Bundling failed",
    // RN app registration failure
    "Application has not been registered",
    // Same failure, alternate phrasing
    "hasn't been registered",
    // React Native LogBox error overlay testid (error state only)
    'data-testid="logbox-overlay"',
    // Metro's own error HTML page title (only rendered on error, not in bundles)
    "<title>Metro Bundler</title>",
  ];
  const lower = html.toLowerCase();
  for (const marker of markers) {
    if (lower.includes(marker.toLowerCase())) return true;
  }
  return false;
}

// ── decision.ts ───────────────────────────────────────────────────────────────
/** Maximum total attempts (0-based attempts 0, 1, 2 → 3 tries). */
export const MAX_ATTEMPTS = 3;

/** Tolerate up to this many consecutive spurious Daytona NotFound responses. */
export const MAX_NOT_FOUND_TOLERANCE = 2;

/** Heartbeat age past which the sandbox is presumed dead. */
export const HEARTBEAT_STALE_MS = 60_000;

export function decide(input) {
  const {
    jobStatus,
    heartbeatAgeMs,
    attempt,
    sandboxState,
    isEdit,
    budgetExhausted,
    turnLimitReached,
    notFoundCount,
  } = input;

  // Completed successfully.
  if (jobStatus === "complete") return "complete";

  // Budget or turn limit exhausted — terminal failure.
  if (budgetExhausted || turnLimitReached) return "fail";

  // Tolerate spurious Daytona NotFound up to MAX_NOT_FOUND_TOLERANCE times.
  if (jobStatus === "not-found") {
    if (notFoundCount <= MAX_NOT_FOUND_TOLERANCE) return "continue";
    // Too many consecutive NotFound → treat death.
    return attempt < MAX_ATTEMPTS - 1
      ? isEdit && attempt === 0
        ? "retry-git-reset"
        : "retry-recreate"
      : "fail";
  }

  // Runner reported failure.
  if (jobStatus === "failed") {
    if (attempt < MAX_ATTEMPTS - 1) {
      return isEdit && attempt === 0 ? "retry-git-reset" : "retry-recreate";
    }
    return "fail";
  }

  // Sandbox stopped = dead.
  if (sandboxState === "stopped") {
    if (attempt < MAX_ATTEMPTS - 1) {
      return isEdit && attempt === 0 ? "retry-git-reset" : "retry-recreate";
    }
    return "fail";
  }

  // Heartbeat stale = presumed dead.
  if (heartbeatAgeMs > HEARTBEAT_STALE_MS) {
    if (attempt < MAX_ATTEMPTS - 1) {
      return isEdit && attempt === 0 ? "retry-git-reset" : "retry-recreate";
    }
    return "fail";
  }

  // Job is running, everything looks healthy.
  return "continue";
}

// ── report.ts ─────────────────────────────────────────────────────────────────
function toNumber(v, fallback = 0) {
  const n = Number(v);
  return Number.isFinite(n) ? n : fallback;
}

function toStringArray(v) {
  if (!Array.isArray(v)) return [];
  return v.filter((x) => typeof x === "string");
}

export function parseRunnerReport(raw) {
  if (typeof raw !== "object" || raw === null) {
    return { valid: false, error: "report must be a non-null object" };
  }
  const obj = raw;

  const ok = typeof obj["ok"] === "boolean" ? obj["ok"] : false;
  const summary = typeof obj["summary"] === "string" ? obj["summary"] : "";
  const entryScreens = toStringArray(obj["entryScreens"]);
  const costUsd = toNumber(obj["costUsd"]);

  const rawUsage =
    typeof obj["usage"] === "object" && obj["usage"] !== null
      ? (obj["usage"])
      : {};

  const usage = {
    inputTokens: toNumber(rawUsage["inputTokens"]),
    outputTokens: toNumber(rawUsage["outputTokens"]),
    cacheReadTokens: toNumber(rawUsage["cacheReadTokens"]),
    cacheWriteTokens: toNumber(rawUsage["cacheWriteTokens"]),
  };

  return {
    valid: true,
    report: { ok, summary, entryScreens, costUsd, usage },
  };
}

// ── token.ts ──────────────────────────────────────────────────────────────────
const ALGO = { name: "HMAC", hash: "SHA-256" };

async function importKey(secret) {
  const enc = new TextEncoder();
  return crypto.subtle.importKey("raw", enc.encode(secret), ALGO, false, [
    "sign",
    "verify",
  ]);
}

function toBase64url(buf) {
  const bytes = buf instanceof Uint8Array ? buf : new Uint8Array(buf);
  return btoa(String.fromCharCode(...bytes))
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "");
}

function fromBase64url(s) {
  const b64 = s.replace(/-/g, "+").replace(/_/g, "/");
  const bin = atob(b64);
  return Uint8Array.from(bin, (c) => c.charCodeAt(0)).buffer;
}

/** Sign a payload and return a compact token: base64url(payload).base64url(sig) */
export async function signToken(
  payload,
  secret,
) {
  const enc = new TextEncoder();
  const payloadB64 = toBase64url(enc.encode(JSON.stringify(payload)));
  const key = await importKey(secret);
  const sig = await crypto.subtle.sign(ALGO, key, enc.encode(payloadB64));
  return `${payloadB64}.${toBase64url(sig)}`;
}

/** Verify a token. Returns the payload if valid, or an error reason. */
export async function verifyToken(
  token,
  secret,
  now = Date.now(),
) {
  const parts = token.split(".");
  if (parts.length !== 2) {
    return { valid: false, reason: "malformed token: expected 2 parts" };
  }
  const [payloadB64, sigB64] = parts;

  const key = await importKey(secret);
  const enc = new TextEncoder();
  let isValid ;
  try {
    isValid = await crypto.subtle.verify(
      ALGO,
      key,
      fromBase64url(sigB64),
      enc.encode(payloadB64),
    );
  } catch {
    return { valid: false, reason: "signature verification error" };
  }

  if (!isValid) return { valid: false, reason: "signature mismatch" };

  let payload ;
  try {
    payload = JSON.parse(new TextDecoder().decode(fromBase64url(payloadB64)));
  } catch {
    return { valid: false, reason: "payload JSON parse error" };
  }

  if (
    typeof payload !== "object" ||
    payload === null ||
    typeof (payload)["versionId"] !== "string" ||
    typeof (payload)["exp"] !== "number"
  ) {
    return { valid: false, reason: "payload shape invalid" };
  }

  const typed = payload;
  if (now > typed.exp) {
    return { valid: false, reason: "token expired" };
  }

  return { valid: true, payload: typed };
}

// ── tsc follow-up turn builder ────────────────────────────────────────────────
function buildTscFollowUpTurn(errorBlock) {
  return [
    "TypeScript errors were found after your changes. Please fix them.",
    "",
    "```",
    errorBlock,
    "```",
    "",
    "Run `npx tsc --noEmit --pretty false` after your edits to verify they are resolved.",
  ].join("\n");
}

// ═══════════════════════════════════════════════════════════════════════════════
// SELF-TEST (--self-test flag — no network, no SDK)
// ═══════════════════════════════════════════════════════════════════════════════

function runSelfTests() {
  let passed = 0;
  let failed = 0;

  function assert(condition, label) {
    if (condition) {
      passed++;
    } else {
      console.error(`FAIL: ${label}`);
      failed++;
    }
  }

  // forbidden
  assert(FORBIDDEN_PATHS.has("package.json"), "FORBIDDEN_PATHS has package.json");
  assert(isForbiddenPath("./tsconfig.json"), "isForbiddenPath strips ./");
  assert(!isForbiddenPath("app/index.tsx"), "isForbiddenPath allows app files");

  // overlay
  assert(looksLikeMetroOverlay("Unable to resolve module foo"), "overlay: Unable to resolve");
  assert(looksLikeMetroOverlay("Bundling failed"), "overlay: Bundling failed");
  assert(!looksLikeMetroOverlay("<html><body>Hello</body></html>"), "overlay: healthy html");

  // decision
  assert(
    decide({ jobStatus: "complete", heartbeatAgeMs: 0, attempt: 0, sandboxState: "running", tscCycle: 0, isEdit: false, budgetExhausted: false, turnLimitReached: false, notFoundCount: 0 }) === "complete",
    "decide: complete",
  );
  assert(
    decide({ jobStatus: "running", heartbeatAgeMs: 0, attempt: 0, sandboxState: "running", tscCycle: 0, isEdit: false, budgetExhausted: false, turnLimitReached: false, notFoundCount: 0 }) === "continue",
    "decide: continue",
  );
  assert(
    decide({ jobStatus: "failed", heartbeatAgeMs: 0, attempt: 0, sandboxState: "running", tscCycle: 0, isEdit: true, budgetExhausted: false, turnLimitReached: false, notFoundCount: 0 }) === "retry-git-reset",
    "decide: retry-git-reset for isEdit",
  );

  // report
  const r = parseRunnerReport({ ok: true, summary: "ok", entryScreens: [], costUsd: 1, usage: { inputTokens: 10, outputTokens: 5, cacheReadTokens: 0, cacheWriteTokens: 0 } });
  assert(r.valid === true, "parseRunnerReport: valid payload");
  const bad = parseRunnerReport(null);
  assert(bad.valid === false, "parseRunnerReport: null is invalid");

  // tsc follow-up
  const turn = buildTscFollowUpTurn("error TS2345: foo");
  assert(turn.includes("error TS2345: foo"), "buildTscFollowUpTurn: includes error");
  assert(turn.includes("TypeScript errors"), "buildTscFollowUpTurn: includes preamble");

  console.log(`Self-test: ${passed} passed, ${failed} failed`);
  if (failed > 0) process.exit(1);
}

// ═══════════════════════════════════════════════════════════════════════════════
// RUNNER
// ═══════════════════════════════════════════════════════════════════════════════

if (process.argv.includes("--self-test")) {
  runSelfTests();
  process.exit(0);
}

const {
  ANTHROPIC_API_KEY,
  CONVEX_URL,
  JOB_TOKEN,
  versionId,
  threadId,
  promptMessageId,
  model,
  effort,
  kit,
  isEdit: isEditEnv,
  styleDirective,
} = process.env;

// ── Bridge: outbound-only Convex mutations via plain HTTP ─────────────────────
// Plan §1/G6: poll-only, no inbound HTTP surface, no custom auth header.
// JOB_TOKEN is passed as an HMAC arg so convex/agentBridge.ts can verify it.
// Endpoint: POST {CONVEX_URL}/api/mutation  { path, args }

async function bridgeMutation(fnPath, args) {
  const res = await fetch(`${CONVEX_URL}/api/mutation`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      path: fnPath,
      args: { jobToken: JOB_TOKEN, ...args },
      format: "json",
    }),
  });
  if (!res.ok) {
    throw new Error(`bridge ${fnPath} returned HTTP ${res.status}`);
  }
  const body = await res.json();
  if (body.status === "error") {
    throw new Error(`bridge ${fnPath} error: ${body.errorMessage}`);
  }
  return body.value ?? null;
}

// ── Heartbeat ─────────────────────────────────────────────────────────────────

const HEARTBEAT_INTERVAL_MS = 15_000;
let heartbeatTimer = null;

function startHeartbeat() {
  heartbeatTimer = setInterval(async () => {
    try {
      await bridgeMutation("agentBridge:heartbeat", { versionId });
    } catch (err) {
      console.warn("[runner] heartbeat failed:", err.message);
    }
  }, HEARTBEAT_INTERVAL_MS);
  heartbeatTimer.unref?.();
}

function stopHeartbeat() {
  if (heartbeatTimer) {
    clearInterval(heartbeatTimer);
    heartbeatTimer = null;
  }
}

// ── File mirror batching (300ms debounce) ─────────────────────────────────────
// PostToolUse Write/Edit hooks accumulate writes; a 300ms debounce batches
// them into a single bridge.mirrorFile call per burst.

const MIRROR_DEBOUNCE_MS = 300;
let mirrorPending = new Map(); // path → contents
let mirrorTimer = null;

async function flushMirror() {
  if (mirrorPending.size === 0) return;
  const batch = Object.fromEntries(mirrorPending);
  mirrorPending = new Map();
  try {
    await bridgeMutation("agentBridge:mirrorFile", { versionId, files: batch });
  } catch (err) {
    console.warn("[runner] mirrorFile failed:", err.message);
  }
}

function scheduleMirror(filePath, contents) {
  mirrorPending.set(filePath, contents);
  if (mirrorTimer) clearTimeout(mirrorTimer);
  mirrorTimer = setTimeout(flushMirror, MIRROR_DEBOUNCE_MS);
}

// ── Chat delta streaming ───────────────────────────────────────────────────────
// Word-chunk throttle: accumulate text from assistant message events and
// flush to appendChatDelta once per word boundary or on explicit flush.

let deltaBuffer = "";
let deltaTimer = null;
const DELTA_FLUSH_MS = 80; // ~80ms chunk cadence

function scheduleDelta(text) {
  deltaBuffer += text;
  if (deltaTimer) return;
  deltaTimer = setTimeout(async () => {
    deltaTimer = null;
    if (!deltaBuffer) return;
    const chunk = deltaBuffer;
    deltaBuffer = "";
    try {
      await bridgeMutation("agentBridge:appendChatDelta", { versionId, threadId, chunk });
    } catch (err) {
      console.warn("[runner] appendChatDelta failed:", err.message);
    }
  }, DELTA_FLUSH_MS);
}

async function flushDelta() {
  if (deltaTimer) { clearTimeout(deltaTimer); deltaTimer = null; }
  if (!deltaBuffer) return;
  const chunk = deltaBuffer;
  deltaBuffer = "";
  try {
    await bridgeMutation("agentBridge:appendChatDelta", { versionId, threadId, chunk });
  } catch (err) {
    console.warn("[runner] appendChatDelta flush failed:", err.message);
  }
}

// ── tsc verify (runs locally inside the sandbox box) ─────────────────────────
// tsc is invoked with execSync — it's a local process, no bridge round-trip.

import { execSync } from "node:child_process";

function runTscLocally(cwd) {
  try {
    execSync("npx tsc --noEmit --pretty false", { cwd, stdio: "pipe", timeout: 60_000 });
    return { hasErrors: false, output: "" };
  } catch (err) {
    const output = (err.stdout?.toString() ?? "") + (err.stderr?.toString() ?? "");
    return { hasErrors: true, output: output.trim() };
  }
}

// ── Main runner ───────────────────────────────────────────────────────────────
// Agent SDK API (code.claude.com/docs/en/agent-sdk/typescript):
//   query({ prompt, options }) → AsyncGenerator<SDKMessage>
//   options.permissionMode = "dontAsk"  (camelCase per docs)
//   options.allowedTools   = ["Read","Write","Edit","Bash","Glob","Grep"]
//   options.hooks.preToolUse  / postToolUse — { match: { toolName }, handler }
//   Write hook input: { path, content }; Edit hook input: { path, edits[] }
//   Multi-turn tsc feedback: q.streamInput(asyncIterable) on the active query

const APP_CWD = "/home/daytona/expo-app";
const MAX_TSC_CYCLES = 4;

// Build an AsyncIterable<SDKUserMessage> from a single string message.
async function* singleUserMessage(text) {
  yield { type: "user", message: { role: "user", content: text } };
}

async function run() {
  startHeartbeat();

  try {
    // Dynamic import — SDK is installed in the nw2 snapshot, not in this repo.
    const { query } = await import("@anthropic-ai/claude-agent-sdk");

    // The initial prompt arrives via env: promptMessageId identifies the
    // message in the Convex thread. The actual text is baked into that message;
    // the bridge fetches it and returns it as the prompt string.
    const promptText = await bridgeMutation("agentBridge:getPromptText", {
      versionId,
      promptMessageId,
    });

    let tscCycle = 0;

    // Hooks wired to the SDK's documented tool names and input shapes.
    // preToolUse: write-deny FORBIDDEN_PATHS (deny before the write happens).
    // postToolUse: mirror Write/Edit to Convex via the 300ms batcher.
    const hooks = {
      preToolUse: [
        {
          match: { toolName: "Write" },
          handler: async (hook) => {
            if (isForbiddenPath(hook.input.path ?? "")) {
              return {
                behavior: "deny",
                message: `Refusing to write forbidden path: ${hook.input.path}`,
              };
            }
          },
        },
        {
          match: { toolName: "Edit" },
          handler: async (hook) => {
            if (isForbiddenPath(hook.input.path ?? "")) {
              return {
                behavior: "deny",
                message: `Refusing to edit forbidden path: ${hook.input.path}`,
              };
            }
          },
        },
      ],
      postToolUse: [
        {
          match: { toolName: "Write" },
          handler: async (hook) => {
            if (hook.input.path && !isForbiddenPath(hook.input.path)) {
              scheduleMirror(hook.input.path, hook.input.content ?? "");
            }
          },
        },
        {
          match: { toolName: "Edit" },
          handler: async (hook) => {
            // After an Edit the file has been modified; read it back for mirroring.
            if (hook.input.path && !isForbiddenPath(hook.input.path)) {
              try {
                const { readFileSync } = await import("node:fs");
                const contents = readFileSync(
                  `${APP_CWD}/${hook.input.path}`,
                  "utf8",
                );
                scheduleMirror(hook.input.path, contents);
              } catch {
                // Best-effort; mirror will be stale but not fatal.
              }
            }
          },
        },
      ],
    };

    // Launch the query. The SDK returns an AsyncGenerator; we iterate it to
    // consume assistant messages and tool events, streaming text deltas to
    // Convex via appendChatDelta.
    const q = query({
      prompt: promptText,
      options: {
        model: model || "claude-opus-4-8",
        permissionMode: "dontAsk",
        allowedTools: ["Read", "Write", "Edit", "Bash", "Glob", "Grep"],
        maxTurns: 40,
        cwd: APP_CWD,
        hooks,
      },
    });

    for await (const message of q) {
      // Stream assistant text deltas to Convex.
      if (message.type === "assistant" && message.message?.content) {
        for (const block of message.message.content) {
          if (block.type === "text" && block.text) {
            scheduleDelta(block.text);
          }
        }
      }
    }

    await flushDelta();
    await flushMirror();

    // tsc verify loop — runs locally in the sandbox, feeds errors back via
    // q.streamInput() as per the SDK's multi-turn documented mechanism.
    // Each cycle is a new query() because the first query has already
    // completed; we pass the tsc error as the follow-up prompt.
    while (tscCycle < MAX_TSC_CYCLES) {
      const { hasErrors, output } = runTscLocally(APP_CWD);
      if (!hasErrors) break;

      tscCycle++;
      console.log(`[runner] tsc cycle ${tscCycle}: errors found, feeding back`);

      const fixQ = query({
        prompt: buildTscFollowUpTurn(output),
        options: {
          model: model || "claude-opus-4-8",
          permissionMode: "dontAsk",
          allowedTools: ["Read", "Write", "Edit", "Bash", "Glob", "Grep"],
          maxTurns: 10,
          cwd: APP_CWD,
          hooks,
        },
      });

      for await (const message of fixQ) {
        if (message.type === "assistant" && message.message?.content) {
          for (const block of message.message.content) {
            if (block.type === "text" && block.text) {
              scheduleDelta(block.text);
            }
          }
        }
      }

      await flushDelta();
      await flushMirror();
    }

    // Final tsc check to determine ok/fail status.
    const { hasErrors: finalErrors } = runTscLocally(APP_CWD);

    const report = {
      ok: !finalErrors,
      summary: finalErrors
        ? `tsc still has errors after ${tscCycle} repair cycle(s)`
        : "Agent run complete — tsc clean",
      entryScreens: [],
      costUsd: 0,
      usage: { inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0 },
    };

    await bridgeMutation("agentBridge:complete", { versionId, report });
  } catch (err) {
    console.error("[runner] fatal:", err);
    await bridgeMutation("agentBridge:fail", { versionId, reason: String(err) }).catch(() => {});
    process.exit(1);
  } finally {
    stopHeartbeat();
  }
}

run();
